"""blocked_fixed

Revision ID: 4d127852617c
Revises: f394892d3964
Create Date: 2019-12-13 01:52:48.926188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d127852617c'
down_revision = 'f394892d3964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked',
    sa.Column('blocker_id', sa.Integer(), nullable=True),
    sa.Column('blocked_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['user.id'], )
    )
    op.drop_table('blockers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockers',
    sa.Column('blocker_id', sa.INTEGER(), nullable=True),
    sa.Column('blocked_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], [u'user.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], [u'user.id'], )
    )
    op.drop_table('blocked')
    # ### end Alembic commands ###
