"""followers

Revision ID: 648b36470593
Revises: 53dafe74c106
Create Date: 2019-12-12 17:42:21.635777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648b36470593'
down_revision = '53dafe74c106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
